Add new integration for Parad
SEKOIA-IO/intake-formats pull request #1106
Opened 2024-06-11 08:52 UTC by LICHTENBERGERHugo

2024-06-11 10:04 UTC, squioc requested changes
Thanks for your contribution.
There are some changes to apply to the format. Thank you.

2024-06-11 10:04 UTC, squioc commented on Daspren/daspren-parad/tests/file_opened.json
Can you apply the linter on this file?
In the directory `utils`, type `poetry utils/linter.py fix --changes`

2024-06-11 10:04 UTC, squioc commented on Daspren/daspren-parad/tests/malicious_behavior.json
Can you apply the linter on this file?
In the directory `utils`, type `poetry utils/linter.py fix --changes`

2024-06-11 10:04 UTC, squioc commented on Daspren/daspren-parad/ingest/parser.yml
> +        observer.type: "dlp-solution"
Indentation issue.
```suggestion
          observer.vendor: "Daspren"
          observer.product: "Parad"
          observer.type: "dlp-solution"
```

2024-06-11 11:49 UTC, squioc requested changes

2024-06-11 11:49 UTC, squioc commented on Daspren/daspren-parad/tests/file_opened.json
> +    "message": "{\"time\":\"2024-03-04T10:43:31.337737900+01:00\",\"level\":\"INFO\",\"message\":\"File opened\",\"event_data\":{\"basename\":\"AppData\",\"created_length\":\"0\",\"executable\":\"C:\
We detected that the json in `message` seems to be malformed. Can you check it? Thanks.
According to our analysis, it seems to be the backslashes in the fields `executable` and `fullpath` that generate the issue.

2024-06-11 15:26 UTC, LICHTENBERGERHugo commented on Daspren/daspren-parad/ingest/parser.yml
> +        event.kind: "event"
Done

2024-06-11 15:26 UTC, LICHTENBERGERHugo commented on Daspren/daspren-parad/ingest/parser.yml
> +        observer.type: "dlp-solution"
Done

2024-06-14 08:52 UTC, squioc requested changes
Hello,
we detected some mismatching between the parser and the tests.
We add some suggestions

2024-06-14 08:52 UTC, squioc commented on Daspren/daspren-parad/tests/file_opened.json
can you update the test according to the last changes? Thanks
```
$ cd utils/
$ poetry run pytest test_formats.py --format=daspren-parad --fix-expectations
```

2024-06-14 08:52 UTC, squioc commented on Daspren/daspren-parad/tests/malicious_behavior.json
Can you update the test according to the last changes? Thanks
```
$ cd utils/
$ poetry run pytest test_formats.py --format=daspren-parad --fix-expectations
```

2024-06-14 08:52 UTC, squioc commented on Daspren/daspren-parad/ingest/parser.yml
> +          daspren.process.hash.blake3: "{{json.event.hash}}"
According to the tests, file_opened.json's event contains information in the `event_data` property, while for the malicious_behaviour.json's message contains information at the root.
We suggest modifying these lines:
```suggestion
          process.name: "{{json.event.executable_basename or json.event.event_data.executable_basename}}"
          process.executable: "{{json.event.executable or json.event.event_data.executable}}"
          process.pid: "{{json.event.pid or json.event.event_data.pid}}"
          process.parent.pid: "{{json.event.ppid or json.event.event_data.ppid}}"
          daspren.process.hash.blake3: "{{json.event.hash or json.event.event_data.hash}}"
```

2024-06-14 08:52 UTC, squioc commented on Daspren/daspren-parad/ingest/parser.yml
> +          file.path: "{{json.event.fullpath}}"
sames here:
```suggestion
          file.name: "{{json.event.basename or json.event.event_data.basename}}"
          file.path: "{{json.event.fullpath or json.event.event_data.fullpath}}"
```

2024-06-14 08:52 UTC, squioc commented on Daspren/daspren-parad/ingest/parser.yml
> +          process.code_signature.exists: "{{json.event.signed}}"
same here:
```suggestion
          process.code_signature.exists: "{{json.event.signed or json.event.event_data.signed}}"
```

2024-06-14 12:26 UTC, merged