adding fields for format wallix-bastion to session integrity event
SEKOIA-IO/intake-formats pull request #1245
Opened 2024-09-03 14:49 UTC by soc-dstny

2024-09-05 14:00 UTC, squioc commented on Wallix/wallix-bastion/tests/session_integrity.json
> +    "message": "2024-09-01T00:06:15+02:00 foo-bastion-bar WAB(root) 5946 - - [sessionintegrity] session_uid=\"1830c403be7caf0c00505688c380\" status=\"failed\" type=\"SSH_SHELL_SESSION\" user=\"adm@CO
```suggestion
    "message": "[sessionintegrity] session_uid=\"1830c403be7caf0c00505688c380\" status=\"failed\" type=\"SSH_SHELL_SESSION\" user=\"adm@CORP.NET@1.1.1.1\" target=\"domain@local@target01.corp.net:SSH_1\" begin=\"2022-08-19 11:31:17\" end=\"2022-08-19 11:32:50\" files=[/var/wab/remote/recorded/ssh/2022-08-19/182b5714b466cba10050568e16d9,adm@CORP.NET@1.1.1.1,domain@target01.corp.net,20220819-113117,foo-bastion-bar.corp.net,1805.ttyrec]",
```

2024-09-05 16:03 UTC, squioc requested changes

2024-09-05 16:03 UTC, squioc commented on Wallix/wallix-bastion/tests/session_integrity.json
> +    "message": "2024-09-01T00:06:15+02:00 foo-bastion-bar WAB(root) 5946 - - [sessionintegrity] session_uid=\"1830c403be7caf0c00505688c380\" status=\"failed\" type=\"SSH_SHELL_SESSION\" user=\"adm@CO
The syslog header is still present in this part of the test:
```suggestion
    "message": "[sessionintegrity] session_uid=\"1830c403be7caf0c00505688c380\" status=\"failed\" type=\"SSH_SHELL_SESSION\" user=\"adm@CORP.NET@1.1.1.1\" target=\"domain@local@target01.corp.net:SSH_1\" begin=\"2022-08-19 11:31:17\" end=\"2022-08-19 11:32:50\" files=[/var/wab/remote/recorded/ssh/2022-08-19/182b5714b466cba10050568e16d9,adm@CORP.NET@1.1.1.1,domain@target01.corp.net,20220819-113117,foo-bastion-bar.corp.net,1805.ttyrec]",
```

2024-09-06 07:28 UTC, soc-dstny commented
My bad, it should be good this time

2024-09-09 16:05 UTC, squioc requested changes
Can you add the `event.type`, also, for the event? Thanks.

2024-09-10 07:24 UTC, squioc approved these changes
LGTM

2024-09-10 07:24 UTC, merged