Proofpoint TAP - fix URL parsing
SEKOIA-IO/intake-formats pull request #1255
Opened 2024-09-05 11:45 UTC by lvoloshyn-sekoia

2024-09-09 13:17 UTC, squioc requested changes
Thanks for the fix.
However, can you keep `threat.enrichments.indicator.url.domain` in addition to `threat.enrichments.indicator.url.original` and create another PR that remove `threat.enrichments.indicator.url.domain`?

2024-09-09 13:17 UTC, squioc commented on ProofPoint/proofpoint-tap/ingest/parser.yml
> +                    "original": "{{threat.threat}}"
Can you add the `url.domain` with the same value in order to do a smooth transition? The field `threat.enrichments.indicator.url.domain` is currently used.

2024-09-10 09:05 UTC, lvoloshyn-sekoia commented
PR with remove - https://github.com/SEKOIA-IO/intake-formats/pull/1261

2024-09-13 07:23 UTC, squioc approved these changes
LGTM

2024-09-13 08:27 UTC, merged