Strict Mode: format (3)
SEKOIA-IO/intake-formats pull request #1340
Opened 2024-11-06 10:51 UTC by lvoloshyn-sekoia

2024-11-07 15:11 UTC, squioc requested changes
Thank you for the work.
I detected issues in some tests.

2024-11-07 15:11 UTC, squioc commented on Wallix/wallix-bastion/ingest/parser.yml
I detected some failures in the following test:
- Wallix/wallix-bastion/tests/rexec.json

2024-11-07 15:11 UTC, squioc commented on Windows/windows/ingest/parser.yml
I detected failures in the following tests:
- Windows/windows/tests/Event_4932.json
- Windows/windows/tests/Event_4933.json
- Windows/windows/tests/notification_subscription.json
- Windows/windows/tests/process_8002.json
- Windows/windows/tests/process_8005.json

2024-11-08 07:21 UTC, lvoloshyn-sekoia commented on Windows/windows/ingest/parser.yml
My bad

2024-11-08 07:22 UTC, lvoloshyn-sekoia commented on Wallix/wallix-bastion/ingest/parser.yml
Somehow missed this. But we don't parse anything in this test. Perhaps we should either delete it or just don't raise errors for the `parsed_event` stage?

2024-11-13 11:29 UTC, squioc commented on Wallix/wallix-bastion/ingest/parser.yml
OK. Indeed, nothing is extracted in this test. I agree to delete it.

2024-11-15 11:03 UTC, squioc approved these changes
LGTM

2024-11-15 11:04 UTC, merged