Add chrome service
SEKOIA-IO/intake-formats pull request #1359
Opened 2024-11-15 15:26 UTC by TOUFIKIzakarya

2024-11-15 17:30 UTC, squioc requested changes
Thank you for the work. Some changes to apply.

2024-11-15 17:30 UTC, squioc commented on Google Cloud/google-report/_meta/smart-descriptions.json
Can you move these smartdescriptions upper? They are overridden by another one

2024-11-15 17:30 UTC, squioc commented on Google Cloud/google-report/ingest/parser.yml
> +          device.id: '{% for param in json_event.message.events[0].parameters %}{% if param.name == "PRODUCT_ID" %}{{param.value}}{% endif %}{% endfor %}'
```suggestion
          device.model.identifier: '{% for param in json_event.message.events[0].parameters %}{% if param.name == "PRODUCT_ID" %}{{param.value}}{% endif %}{% endfor %}'
```

2024-11-15 17:30 UTC, squioc commented on Google Cloud/google-report/ingest/parser.yml
> +          device.model.identifier: '{% for param in json_event.message.events[0].parameters %}{% if param.name == "DEVICE_NAME" %}{{param.value}}{% endif %}{% endfor %}'
```suggestion
          host.name: '{% for param in json_event.message.events[0].parameters %}{% if param.name == "DEVICE_NAME" %}{{param.value}}{% endif %}{% endfor %}'
```

2024-11-15 17:30 UTC, squioc commented on Google Cloud/google-report/ingest/parser.yml
I think you can also extract `VENDOR_NAME` into `device.manufacturer` and `DEVICE_PLATFORM` into `host.os.full`

2024-11-18 10:30 UTC, TOUFIKIzakarya commented on Google Cloud/google-report/ingest/parser.yml
Ok i will do that thanks

2024-11-20 11:32 UTC, squioc submitted a review, later dismissed
LGTM

2024-11-20 11:38 UTC, squioc approved these changes
LGTM

2024-11-20 11:38 UTC, merged