Fix: Fortigate datetime issue
SEKOIA-IO/intake-formats pull request #1372
Opened 2024-11-29 07:49 UTC by vg-svitla

Closes [300](https://github.com/SekoiaLab/integration/issues/300)

2024-11-29 16:42 UTC, squioc requested changes

2024-11-29 16:42 UTC, squioc commented on Fortinet/fortigate/ingest/parser.yml
>          timezone: "UTC"
According to some observations:
The timestamp is the local one from the machine.
The eventtime is a timestamp, in nanosecond, in the UTC timezone

So, for the parsing of the timestamp, I suggest using `{{parsed_event.message.tz}}` as the timezone.

2024-12-12 09:59 UTC, rombernier commented
Hello @vg-svitla, can you also add this update in the PR ? https://github.com/SekoiaLab/integration/issues/320

2024-12-12 10:01 UTC, rombernier commented
Hello, any ETA on this fix ? Thanks

2024-12-12 15:14 UTC, squioc commented
@rombernier No yet. I'm trying to qualify the Fortigate fields with date in order to not introduce a regression in the format.

2024-12-17 17:03 UTC, merged