Update parser.yml
SEKOIA-IO/intake-formats pull request #247
Opened 2022-09-28 12:34 UTC by Men-hau

proposition
ECS field= log.syslog.hostname
Log field: devname

Parent task: #[34044](https://github.com/SekoiaLab/platform/issues/34044)

2022-09-28 12:44 UTC, squioc requested changes

2022-09-28 12:44 UTC, squioc commented on Fortinet/fortigate/ingest/parser.yml
> +          log.syslog.hostname: "{{parsed_event.devname}}"
I think the proper ECS fields is `observer.hostname`. `log.syslog.hostname` contains the hostname extracted from the header of a syslog message.
```suggestion
          observer.hostname: "{{parsed_event.devname}}"
```

2022-09-28 15:08 UTC, PierrickV submitted a review, later dismissed

2022-09-29 09:18 UTC, squioc submitted a review, later dismissed

2022-09-30 07:55 UTC, PierrickV reviewed
I don't see why the tests files where not affected by your change

2022-09-30 10:16 UTC, PierrickV commented
I found a typo on this PR.

I will let @squioc please review since I made the change

2022-09-30 10:17 UTC, squioc approved these changes

2022-09-30 13:46 UTC, merged