Change name and logos of specific intakes
SEKOIA-IO/intake-formats pull request #288
Opened 2022-11-02 15:30 UTC by ka0ula

Based on this document: https://www.notion.so/Renommage-des-intakes-dans-l-OC-et-dans-la-documentation-b4dd83a9c88f48fabd95eabedd9948a9

2022-11-03 16:00 UTC, squioc approved these changes
Be aware that slugs are used to generate automatic parts of the documentation.
Once this PR merged, we should update the documentation related to these formats

2022-11-03 23:25 UTC, otetard approved these changes

2022-11-10 12:44 UTC, squioc requested changes

2022-11-10 12:44 UTC, squioc commented on Broadcom/symantec-endpoint-protection/_meta/manifest.yml
> +slug: symantec-broadcom-endpoint-security
I prefer `<vendor>-<product name>`
```suggestion
slug: broadcom-symantec-endpoint-security
```

2022-11-10 16:05 UTC, merged