Adding palo cortex xdr intake
SEKOIA-IO/intake-formats pull request #291
Opened 2022-11-03 00:15 UTC by m-242

2022-11-04 13:56 UTC, gbossert commented
Awesome :clap: Thank you very much for your contribution.

2022-11-05 14:28 UTC, m-242 commented
Les tests automatisés passent localement, donc je suppose qu'ils passeront également ici.

Ceci dit, il n'y a pour le moment qu'un seul test unitaire de l'intake, en rajouter quelques uns me semble nécéssaire, je ne sais juste pas encore lesquels

2022-11-15 10:42 UTC, m-242 commented
Added another case of test, I don't see much else to add, but suggestions are welcome

2022-11-21 14:46 UTC, squioc requested changes
Thanks for our contribution.
Find below our suggestions for this format.

For any questions, don't hesitate to call our support or to see our [Contribution Guide](https://github.com/SEKOIA-IO/intake-formats/blob/main/CONTRIBUTING.md)

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/manifest.yml
> +uuid: 00000000-0000-0000-0000-000000000000
You can provide any non-existing (in this repository) uuid
```suggestion
uuid: 2652d6b3-242b-4561-9b34-4896f75d3770
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/ingest/parser.yml
> +          cortexxdr.shost: '{{parsed_event.message.shost}}'
Please use [ECS fields](https://www.elastic.co/guide/en/ecs/8.4/ecs-event.html) as the base of your taxonomy.
For example, here, [`host.name`](https://www.elastic.co/guide/en/ecs/8.4/ecs-host.html#field-host-name) is more suitable.
```suggestion
          host.name: '{{parsed_event.message.shost}}'
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/ingest/parser.yml
> +          cortexxdr.suser: '{{parsed_event.message.suser}}'
According to your tests, `suser` contains the username and the user's domain (e.g: `domain\\user`).
I suggest extracting this two information:
```suggestion
          user.name: '{{parsed_event.message.suser.split("\\"}[1]}'
           user.domain: '{{parsed_event.message.suser.split("\\"}[0]}'
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/ingest/parser.yml
> +          cortexxdr.action: '{{parsed_event.message.act|lower}}'
[`event.action`](https://www.elastic.co/guide/en/ecs/8.4/ecs-event.html#field-event-action) is more suitable:
```suggestion
          event.action: '{{parsed_event.message.act|lower}}'
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/ingest/parser.yml
> +          cortexxdr.severity_human: '{{parsed_event.message.Severity}}'
[`event.severity`](https://www.elastic.co/guide/en/ecs/8.4/ecs-event.html#field-event-severity) seems more suitable:
```suggestion
          event.severity: '{{parsed_event.message.Severity}}'
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/ingest/parser.yml
> +          cortexxdr.original_message: '{{parsed_event.message.msg}}'
Original message is already present in the resulting event (in the message field).
```suggestion
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/ingest/parser.yml
> +          cortexxdr.severity_human: cortexxdr.severity_human
According to the suggestion above:
```suggestion
          event.severity: cortexxdr.severity_human
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/smart-descriptions.json
> +    "value": "{cortexxdr.category}: An event of {cortexxdr.severity_human} severity was {cortexxdr.action} on endpoint {cortexxdr.shost}, initiated by user {cortexxdr.suser.0}.",
According to the suggestion in the parser:
```suggestion
    "value": "{cortexxdr.category}: An event of {cortexxdr.severity_human} severity was {event.action} on endpoint {host.name}, initiated by user {user.domain}\\{user.name}.",
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/smart-descriptions.json
> +        "field": "cortexxdr.action"
```suggestion
        "field": "event.action"
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/smart-descriptions.json
> +        "field": "cortexxdr.shost"
```suggestion
        "field": "host.name"
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/smart-descriptions.json
> +      }
```suggestion
      {
        "field": "user.domain"
      },
      {
        "field": "user.name"
      }
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/smart-descriptions.json
> +    "value": "{cortexxdr.category}: {cortexxdr.original_message}",
The original message already exists in the field `message`
```suggestion
    "value": "{cortexxdr.category}: {message}",
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/smart-descriptions.json
> +        "field": "cortexxdr.original_message"
```suggestion
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/fields.yml
> +  type: keyword
According to the suggestion in the parser, these fields become unnecessary.
```suggestion
```

2022-11-21 14:46 UTC, squioc commented on Palo Alto Networks/paloalto-cortex/_meta/fields.yml
> +  type: keyword
The field ECS [`message`](https://www.elastic.co/guide/en/ecs/8.4/ecs-base.html#field-message) already holds the original message.
```suggestion
```

2022-11-21 15:15 UTC, m-242 commented
Thanks a lot for your review, I'll test these locally and come back to you.

2022-11-21 16:38 UTC, m-242 commented
I put @squioc 's recommandations in place, and fixed a few bugs and tests that came in the way.
One bug that I think is worth noting is the way the CEF `suser` field isn't parsed as a string and not an array, which forced me to use some buggy workaround in the parser that I explained in a comment.
This shouldn't be much of a problem for now, as cortex doesn't seem to send multiple users for events very often.

2022-12-02 09:00 UTC, squioc submitted a review, later dismissed

2022-12-07 14:40 UTC, m-242 commented
I didn't mean to dismiss @squioc 's review, especially that I haven't changed anything in the PR except keeping the branch up to date with `main`.

2022-12-07 14:51 UTC, squioc approved these changes

2022-12-07 14:53 UTC, squioc commented
@m-242 Don't worry. Github is very strict about merge and rebase.
To keep your branch updated, you can use the button 'Update branch'; Normally, that does not dismiss reviews.

2022-12-07 14:54 UTC, m-242 commented
Thanks a lot, I will in the future :)

2024-07-15 14:41 UTC, closed without merging