Netwrix intake
SEKOIA-IO/intake-formats pull request #319
Opened 2022-12-01 16:32 UTC by m-242

This is a netwrix intake that leverages the [CEF export addon for netwrix](https://www.netwrix.com/generic_siem_integration.html).

I have a wiki page describing setup (in french), in case it may be helpful to you.

I haven't been able to test all the log kinds provided by Netwrix, as I don't use all product they support, however, Exchange Logs, Sharepoint logs and logon activity logs are parsed.

2022-12-02 08:31 UTC, squioc requested changes
Thanks for your work.
Here, some improvements for the parser.

2022-12-02 08:31 UTC, squioc commented on Netwrix/netwrix_auditor/ingest/parser.yml
> +          server.address: '{{ cef_parser.message.shost }}'
To preserve the semantics of `shost`, I suggest using `source.domain`:
```suggestion
          source.domain: '{{ cef_parser.message.shost }}'
```

2022-12-02 08:31 UTC, squioc commented on Netwrix/netwrix_auditor/ingest/parser.yml
> +          event.start: '{{ cef_parser.message.start }}'
You can also add information about the observer:
```suggestion
          event.start: '{{ cef_parser.message.start }}'
           observer.vendor: '{{parsed_event.message.DeviceVendor}}'
          observer.product: '{{parsed_event.message.DeviceProduct}}'
          observer.version: '{{parsed_event.message.DeviceVersion}}'
```

2022-12-02 08:31 UTC, squioc commented on Netwrix/netwrix_auditor/ingest/parser.yml
> +          event.category: '{{ cef_parser.message.DeviceEventClassID |lower }}'
`event.code` is more suitable for this information
```suggestion
          event.code: '{{ cef_parser.message.DeviceEventClassID |lower }}'
```
<br/>

`event.category` has restricted values (see [ECS specification](https://www.elastic.co/guide/en/ecs/8.4/ecs-allowed-values-event-category.html#ecs-event-category-configuration)). I suggest for `event.category` to use `['configuration']` and for `event.type`, to use `['change']` according the tests.

2022-12-02 08:31 UTC, squioc commented on Netwrix/netwrix_auditor/ingest/parser.yml
> +          event.kind: '{{ cef_parser.message.DeviceProduct }}'
The value for `event.kind` are [restricted](https://www.elastic.co/guide/en/ecs/8.4/ecs-allowed-values-event-kind.html). I suggest to use `event` as value.
```suggestion
          event.kind: 'event'
```

2022-12-02 14:27 UTC, m-242 commented
Thanks for your review.
I applied your changes, but we are losing some information now that the data that was in `event.kind` isn't put in a field.
I need it for the smart descriptions, would it be a problem to have it in another field ?

2022-12-05 15:04 UTC, squioc commented on Netwrix/netwrix_auditor/ingest/parser.yml
> +          event.start: '{{ cef_parser.message.start }}'
I think you should use the stage date to parse this date in the message as [`event.start`](https://www.elastic.co/guide/en/ecs/8.4/ecs-event.html#field-event-start) accept date type (ie [RFC3339](https://www.rfc-editor.org/rfc/rfc3339#page-10) formatted date)

2022-12-05 15:04 UTC, squioc commented on Netwrix/netwrix_auditor/ingest/parser.yml
> +          file.path: '{{ cef_parser.message.filePath.split("/")[3:] |join("/") }}'
You can also provide `file.name` and `file.directory`:
```suggestion
          file.path: '{{ cef_parser.message.filePath.split("/")[3:] |join("/") }}'
          file.directory: '{{ cef_parser.message.filePath.split("/")[3:] |join("/") | dirname }}'
          file.name: '{{ cef_parser.message.filePath | basename }}'
```

2022-12-08 14:40 UTC, squioc approved these changes
Looks good. Thanks for the contribution

2023-01-06 15:22 UTC, merged