Feat/proofpoint/pod/add message parts parsing
SEKOIA-IO/intake-formats pull request #414
Opened 2023-03-14 09:41 UTC by Adamowoc

Add "msgParts" handling to proofpoint parser since we split the messages.

2023-03-14 13:53 UTC, squioc approved these changes

2023-03-14 14:39 UTC, squioc approved these changes

2023-03-14 14:39 UTC, squioc commented on ProofPoint/proofpoint-pod/_meta/smart-descriptions.json
> +        "value": "{email.attachments.file.name}, of type: {email.attachments.file.mime_type} , size: {email.attachments.file.size}bytes, associated with {email.local_id}",
```suggestion
        "value": "{email.attachments.file.name}, of type: {email.attachments.file.mime_type} and size: {email.attachments.file.size} bytes, was attached to {email.local_id}",
```

2023-03-14 14:41 UTC, squioc requested changes

2023-03-14 14:41 UTC, squioc commented on ProofPoint/proofpoint-pod/ingest/parser.yml
> +              "{{url.url}}",
To be coherent with the removed block.
```suggestion
              {% if url.url | is_url %}"{{url.url}}",{% endif %}
```

2023-03-14 14:51 UTC, squioc submitted a review, later dismissed

2023-03-15 20:36 UTC, Adamowoc commented
I fixed the bug, removed msgParts from the tests and added a msgParts test.

2023-03-16 09:06 UTC, squioc requested changes
Could you merge the stage `set_CTI_fields` in the stage `set_fields_message_parts` and replace, in the jinja expression for `url.original`, `file.name` and `file.hash.*`, `set_fields_for_messages` with `set_fields_for_message_parts`?

2023-03-16 09:14 UTC, squioc approved these changes

2023-03-16 09:14 UTC, merged