Aws guard duty
SEKOIA-IO/intake-formats pull request #433
Opened 2023-03-29 08:05 UTC by LenaigKaliou

Still need to add some particular cases (s.a. anomalous behaviour or evidences) and tests
Still need to add smart descriptions
Some fields doesn't always work (geo fields)

2023-03-29 12:09 UTC, LenaigKaliou commented
Suppression of useless fields
Correction of typos
Some tests were added

2023-03-29 15:54 UTC, LenaigKaliou commented
Added smart descriptions
Added a new test
Added a delete field to avoid two same data in different fields

2023-03-30 10:13 UTC, squioc requested changes

2023-03-30 10:13 UTC, squioc commented on AWS/aws-guardduty/tests/event_ekscluster.json
> +              ]
I think we can remove this field

2023-04-03 12:00 UTC, LenaigKaliou commented
Fields removed
Threat fields enriched
1 new test for ecs cluster

2023-04-04 13:02 UTC, squioc requested changes
Nice work :+1: 
Here are some comments.

2023-04-05 09:48 UTC, LenaigKaliou commented
Changes made
No user_agent.full field, I used user_agent.original but it might be user_agent.os.full (it's not very clear with my logs)
I am not sure that threat.enrichments.indicator is necessary, I put those fields directly in threat.indicator
Change of syntax for files, paths and hashes, put in flattened list for more clarity
I only let the anomalies in additional infos for unusual behavior

2023-04-06 08:46 UTC, squioc requested changes

2023-04-06 08:46 UTC, squioc commented on AWS/aws-guardduty/tests/event_container.json
> +            "file_1": {
```suggestion
            "file": {
```

2023-04-06 08:46 UTC, squioc commented on AWS/aws-guardduty/tests/event_container.json
> +            "file_2": {
Should be in another indicator

2023-04-06 08:46 UTC, squioc commented on AWS/aws-guardduty/tests/event_container.json
> +              "hash": "275a021bbfb6489e54d471899f7db9d1663fc345ec2fe2a2c4538aabf651fd0f"
```suggestion
              "hash": { "sha256": "275a021bbfb6489e54d471899f7db9d1663fc345ec2fe2a2c4538aabf651fd0f"}
```

2023-04-06 08:46 UTC, squioc commented on AWS/aws-guardduty/tests/event_container.json
> +              "hash": "275a021bbfb6489e54d471899f7db9d2363fc345ec2fe2a2c4538aabf651ad0x"
```suggestion
              "hash":  { "sha256": "275a021bbfb6489e54d471899f7db9d2363fc345ec2fe2a2c4538aabf651ad0x"}
```

2023-04-06 09:39 UTC, LenaigKaliou commented
Enrichments fixed

2023-04-11 09:26 UTC, merged