Nginx
SEKOIA-IO/intake-formats pull request #459
Opened 2023-04-18 16:13 UTC by LenaigKaliou

NGINX V1 for migration

2023-04-19 08:12 UTC, squioc commented on NGINX/nginx/ingest/parser.yml
> +  set_json_fields:
Suggesting added this constant ECS fields (maybe `event.type` should be adapted according to the original event: is an access log or an error?)
```suggestion
   set_ecs_fields:
    actions:
      - set:
          event.kind: 'event'
          event.category: ['web']
          event.type: ['access']
          event.dataset: 'access'
          observer.product: 'nginx'
          observer.type: 'WEB server'
          observer.vendor: 'F5'
    set_json_fields:
```

2023-04-19 08:49 UTC, squioc commented on NGINX/nginx/tests/json_delete.json
> +          "proxy_add_x_forwarded_for": "1.2.3.4",
I suggest using `network.forward_ip` for this field

2023-04-19 08:51 UTC, squioc commented on NGINX/nginx/tests/json_delete.json
> +          "request_time": "0.007"
I suggest using `event.duration` (be carrefully, `event.duration` is in nanoseconds)

2023-04-19 08:51 UTC, squioc commented on NGINX/nginx/tests/extended_emptybyte.json
> +        "name": "-"
I suggest filtering `-` values

2023-04-19 08:52 UTC, squioc commented on NGINX/nginx/tests/extended_emptybyte.json
> +        "referrer": "-"
I suggest filtering `-` values

2023-04-19 08:52 UTC, squioc commented on NGINX/nginx/tests/json_get_failed_graylog.json
> +          "timestamp": "2020-06-04T11:17:10+02:00",
I suggest using this field to compute `@timestamp`

2023-04-19 08:53 UTC, squioc commented on NGINX/nginx/tests/json_get_failed_graylog.json
> +          "http_scheme": "https",
I suggest using `network.protocol`

2023-04-19 08:54 UTC, squioc commented on NGINX/nginx/tests/json_get_failed_graylog.json
> +          "nginx_access": "True"
I suggest not using this field, except, maybe to compute `event.type`

2023-04-19 14:04 UTC, LenaigKaliou commented
- Merged json and grok fields in one global field
- Made the fixes highlighted in the first version
- Standardized timestamp in rfc3339

2023-04-19 15:47 UTC, LenaigKaliou commented
- Added timestamp for access log
- Added some info in url fields for error logs

2023-04-20 15:15 UTC, squioc requested changes

2023-04-20 15:15 UTC, squioc commented on NGINX/nginx/ingest/parser.yml
> +          action.name: event.type
Event with category `web` only accept type `access`, `error` or `info` (cf [doc](https://www.elastic.co/guide/en/ecs/8.6/ecs-allowed-values-event-category.html#ecs-event-category-web)).
I suggest deleting this step as we have the step line 170 that will set the `event.type`

2023-04-20 15:15 UTC, squioc commented on NGINX/nginx/ingest/parser.yml
> +            {%- endif -%}
Why not use the stage `date.parse` with format '%d/%b/%Y:%H:%M:%S %z' to parse the time_local?

2023-04-21 07:46 UTC, LenaigKaliou commented
- Made fixes on dates
- Fixes event.type for json logs (line 170 wasn't operational for those)

2023-04-21 07:51 UTC, squioc approved these changes

2023-04-21 08:38 UTC, merged