[Feature] air with additional fields
SEKOIA-IO/intake-formats pull request #502
Opened 2023-05-05 18:08 UTC by vg-svitla

2023-05-09 08:17 UTC, squioc requested changes

2023-05-09 08:17 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          source.domain: '{% for Property in parse_data.ParsedData.Entities %} {{Property.P1SenderDomain}} {% endfor %}'
[`email.from.address`](https://www.elastic.co/guide/en/ecs/current/ecs-email.html#field-email-from-address) seems more suitable. Transform the result as an array.
```suggestion
          email.from.address: '[{% for Property in parse_data.ParsedData.Entities %} "{{Property.P1SenderDomain}}", {% endfor %}]'
```

2023-05-09 08:17 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          destination.user.email: '{% for Property in parse_data.ParsedData.Entities %} {{Property.Recipient}} {% endfor %}'
[`email.to.address`](https://www.elastic.co/guide/en/ecs/current/ecs-email.html#field-email-to-address) seems more suitable. Transform as an array as expected by the field
```suggestion
          email.to.address: '[{% for Property in parse_data.ParsedData.Entities %} "{{Property.Recipient}}", {% endfor %}]'
```

2023-05-09 08:17 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          email.sender.address: '{% for Property in parse_data.ParsedData.Entities %} {{Property.Sender}} {% endfor %}'
According to the tests, these fields are not suitable with the generated values. I suggest creating custom fields that accept an array.

2023-05-09 08:17 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          email.subject: '{% for Property in parse_data.ParsedData.Entities %} {{Property.Subject}} {% endfor %}'
According to the tests, these fields are not suitable with the generated values. I suggest creating custom fields that accept an array.

2023-05-10 08:37 UTC, squioc requested changes

2023-05-10 08:37 UTC, squioc commented on Office 365/o365/_meta/fields.yml
> +  type: keyword
Custom fields must not look similar to ECS one. They must be prefixed with the name of the vendor and the name of the format (see [Taxonomy](https://github.com/SEKOIA-IO/intake-formats/blob/main/doc/taxonomy.md#custom-taxomony))
```suggestion
office365.investigation.email.subjects:
  name: office365.investigation.email.subjects
  description: "A list of email subjects"
  type: array

office365.investigation.email.sender.domains:
  name: office365.investigation.email.sender.domains
  description: "The domain of the sender. Might be an array"
  type: keyword
```

(Do not account of the `email.*` fields declared in this taxonomy; they date from a time the ECS taxonomy was not up-to-date).

2023-05-10 08:37 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          destination.user.email: '[{% for Property in parse_data.ParsedData.Entities %} "{{Property.Recipient}}", {% endfor %}]'
```suggestion
          email.to.address: '[{% for Property in parse_data.ParsedData.Entities %} "{{Property.Recipient}}", {% endfor %}]'
```

2023-05-10 08:37 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          threat.enrichments: '[{% for Property in parse_data.ParsedData.Entities %} "{{Property.Threats}}", {% endfor %}]'
[`threat.enrichments`](https://www.elastic.co/guide/en/ecs/8.6/ecs-threat.html#field-threat-enrichments) expects a list of [`indicators`](https://www.elastic.co/guide/en/ecs/8.6/ecs-threat.html#field-threat-enrichments-indicator).
I think the values are not suitable for this field. I suggest creating a custom field `office365.investigation.threats`.

2023-05-10 12:53 UTC, squioc requested changes

2023-05-10 12:53 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          event.url: '[{% for Property in parse_data.ParsedData.Entities %}{% for Url in Property.Urls %} "{{Url}}", {% endfor %}{% endfor %}]'
```suggestion
          office365.investigation.email.urls: '[{% for Property in parse_data.ParsedData.Entities %}{% for Url in Property.Urls %} "{{Url}}", {% endfor %}{% endfor %}]'
```

2023-05-10 12:53 UTC, squioc commented on Office 365/o365/tests/automated_investigation_and_response.json
> +          }
empty lists

2023-05-10 12:53 UTC, squioc commented on Office 365/o365/ingest/parser.yml
> +          source.ip: '[{% for Property in  parse_data.ParsedData.Entities %} "{{Property.SenderIP}}", {% endfor %}]'
`source.ip` is not a list. I suggest creating a custom field.
```suggestion
          office365.investigation.email.sender.ip: '[{% for Property in  parse_data.ParsedData.Entities %} "{{Property.SenderIP}}", {% endfor %}]'
```

2023-05-10 13:25 UTC, vg-svitla commented on Office 365/o365/ingest/parser.yml
> +        filter: "{{parse_data.ParsedData.Entities != None and parse_data.ParsedData.Entities != []}}"
Yes very good point thank you!

2023-05-11 08:00 UTC, squioc approved these changes

2023-05-11 11:07 UTC, merged