CrowdStrike telemetry integration
SEKOIA-IO/intake-formats pull request #524
Opened 2023-05-16 20:18 UTC by vg-svitla

1. CrowdStrike telemetry integration
2. Fix in test_formats.py to skipp checking `parsing_duration_ms`

2023-07-03 19:29 UTC, squioc requested changes

2023-07-03 19:29 UTC, squioc commented on CrowdStrike/crowdstrike-telemetry/tests/telemetry_event_7.json
> +    "message": "{\"event_simpleName\": \"FirewallDeleteRule\", \"ContextTimeStamp\": \"1687509723.415\", \"UserName\": \"j.doe\", \"ConfigStateHash\": \"2181989539\", \"ContextProcessId\": \"16536425
WE can extract `UserName` into `user.name`

2023-07-03 19:29 UTC, squioc commented on CrowdStrike/crowdstrike-telemetry/ingest/parser.yml
> +          "@timestamp": "{{event_date.datetime}}"
```suggestion
          "@timestamp": "{{event_date.datetime}}"
          "event.action": "{{parsed_event.message.event_simpleName}}"
```

2023-07-05 14:48 UTC, vg-svitla commented on CrowdStrike/crowdstrike-telemetry/ingest/parser.yml
> +          "registry.hive": "MACHINE"
Fixed thank you!

2023-07-05 15:14 UTC, squioc commented on CrowdStrike/crowdstrike-telemetry/ingest/parser.yml
> +          "registry.key": '{{parsed_event.message.RegObjectName.split("\\")[2]}}'
Duplicated with L45.
```suggestion
```

2023-07-05 15:16 UTC, squioc commented on CrowdStrike/crowdstrike-telemetry/ingest/parser.yml
> +          "registry.path": "{{parsed_event.message.RegObjectName}}\\{{parsed_event.message.RegValueName}}"
```suggestion
          "registry.path": "{{"\\".join(parsed_event.message.RegObjectName.split("\\")[2:])}}\\{{parsed_event.message.RegValueName}}"
```

2023-07-05 20:33 UTC, squioc approved these changes
:+1:

2023-07-06 07:10 UTC, merged