Add OGO intake
SEKOIA-IO/intake-formats pull request #529
Opened 2023-05-23 10:09 UTC by Sambogo101

Hello, this PR add OGO intake format.

2023-05-24 09:27 UTC, squioc requested changes
Thanks for your contribution.

Could you add some [tests](https://github.com/SEKOIA-IO/intake-formats/blob/main/doc/testing.md), a [manifest file](https://github.com/SEKOIA-IO/intake-formats/blob/main/doc/format.md#format-_meta-directory) and a logo for the format?

2023-05-31 10:01 UTC, Sambogo101 commented
@squioc tests adjusted with new module name. My bad.

2023-05-31 10:13 UTC, squioc requested changes

2023-05-31 10:13 UTC, squioc commented on OGO/ogo-shield/_meta/manifest.yml
> +description: OGO Shield Web Application Firewall provides protection and performance for your web applications and APIs.
A datasource for the format.
```suggestion
description: OGO Shield Web Application Firewall provides protection and performance for your web applications and APIs.

data_sources:
  Web application firewall logs: OGO protects web applications and APIs
```

2023-05-31 10:13 UTC, squioc commented on OGO/ogo-shield/ingest/parser.yml
> +          event.module: ogo.shield.waf
I will ask our Detection team to add an entry for OGO in this rule

2023-05-31 11:39 UTC, squioc approved these changes

2023-05-31 11:39 UTC, merged