wrong indent
SEKOIA-IO/intake-formats pull request #561
Opened 2023-06-13 10:02 UTC by naegelnajim

2023-06-22 13:28 UTC, TOUFIKIzakarya reviewed
Hi @naegelnajim can we have the parent issue please ?

2023-06-23 15:36 UTC, naegelnajim commented on HarfangLab/harfanglab/tests/dns.json
> +      "pid": 12412,
yes because in Elactic search taxonomy the name of process id is process.pid : https://www.elastic.co/guide/en/ecs/current/ecs-process.html

2023-06-26 07:13 UTC, naegelnajim commented on HarfangLab/harfanglab/tests/authentication.json
> +    "agent": {
Done ✅

2023-06-26 08:16 UTC, Adamowoc requested changes

2023-06-26 08:16 UTC, Adamowoc commented on HarfangLab/harfanglab/tests/authentication.json
> +      "type": " end",
Superfluous space

2023-06-26 08:16 UTC, Adamowoc commented on HarfangLab/harfanglab/_meta/fields.yml
>    description: "A list of objects"
Could you elaborate ?

2023-06-28 07:09 UTC, squioc requested changes

2023-06-28 07:09 UTC, squioc commented on HarfangLab/harfanglab/ingest/parser.yml
> +            {{ type_value.replace('\n', '').replace(' ', '') }}
I suggest using a `translate` action to map `event.type`. That should avoid all the replacement instructions.

2023-06-28 07:09 UTC, squioc commented on HarfangLab/harfanglab/ingest/parser.yml
> +          harfanglab.log_type: "{{json_event.message.log_type}}"
After consideration, I wonder if `event.dataset` is not more suitable?
```suggestion
          event.dataset: "{{json_event.message.log_type}}"
```

2023-06-28 07:09 UTC, squioc commented on HarfangLab/harfanglab/_meta/fields.yml
> +  description: "The type of event log capturing the recorded data"
if replaced by `event.dataset`, it could be removed

2023-06-28 07:10 UTC, squioc commented on HarfangLab/harfanglab/_meta/fields.yml
Could you apply prettier on this file (test in failure)?

2023-06-28 07:38 UTC, naegelnajim commented on HarfangLab/harfanglab/_meta/fields.yml
Yes i'll try, because on pycharm i have a problem with prettier. I'm going to fix it so in the future i could apply Prettier by myself

2023-06-28 16:36 UTC, squioc approved these changes

2023-06-28 17:03 UTC, squioc submitted a review, later dismissed

2023-06-29 07:57 UTC, Adamowoc submitted a review, later dismissed

2023-07-04 11:49 UTC, squioc submitted a review, later dismissed

2023-07-04 11:52 UTC, squioc approved these changes

2023-07-04 13:13 UTC, merged