Add Cisco ISE format
SEKOIA-IO/intake-formats pull request #566
Opened 2023-06-15 08:14 UTC by TOUFIKIzakarya

Hi @squioc, you will find bellow the Cisco ISE format. Please can you review it and tell me if that logic is good or not ? and if there's a better way ?

2023-06-15 10:13 UTC, squioc requested changes
Could you add more tests for network events and add test for miscellaneous events?

2023-06-15 10:13 UTC, squioc commented on Cisco/cisco-ise/tests/test_conf_events.json
> +      "type": ["info"],
The ECS specification allows us defining finer [`event.type`](https://www.elastic.co/guide/en/ecs/8.6/ecs-allowed-values-event-category.html#ecs-event-category-configuration) for a configuration event.
```suggestion
      "type": ["change"],
```
Could you also add test for a  configuration creation

2023-06-15 10:13 UTC, squioc commented on Cisco/cisco-ise/tests/test_netwoork_info_events.json
Typo in the name of this file: test_netwoork_info_events.json (the o is doubled in network)

2023-06-15 10:13 UTC, squioc commented on Cisco/cisco-ise/tests/test_netwoork_warn_events.json
Typo in the name of this file: test_netwoork_info_events.json (the o is doubled in network)

2023-06-16 09:36 UTC, squioc requested changes

2023-06-16 09:36 UTC, squioc commented on Cisco/cisco-ise/tests/test_network_info_events.json
> +      "mac": "A4:57:0:64:47:C0:test1",
This mac address is invalid. Only the first part `A4:57:0:64:47:C0` is the mac address, the second part `test1` seems to be the name of device

2023-06-16 09:37 UTC, squioc reviewed
It seems that the test failed.

2023-06-20 07:53 UTC, TOUFIKIzakarya commented on Cisco/cisco-ise/_meta/smart-descriptions.json
> +    "value": " Connection from {source.ip} to the server {source.domain} and this is the reason",
Oh yes, thank you for that Océane.

2023-06-20 07:56 UTC, TOUFIKIzakarya commented on Cisco/cisco-ise/ingest/parser.yml
> +        filter: '{{parsed_kv_sentence.result.get("Device Name") != None and "Configuration" not in parsed_event.message.reason}}'
Ok, so I need to modify it in all other filters. Thank you.

2023-06-23 08:45 UTC, Adamowoc approved these changes

2023-06-23 08:53 UTC, Adamowoc requested changes

2023-06-23 08:53 UTC, Adamowoc commented on Cisco/cisco-ise/tests/test_miscellaneous1.json
> +    "message": "2023-06-07 04:26:17.306 +0200 60198 INFO null: MnT purge event occurred, MESSAGE=completed successfully,"
Could you parse the "MESSAGE=completed successfully" and set [event.outcome](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-outcome.html) with it?

2023-06-23 13:31 UTC, Adamowoc commented on Cisco/cisco-ise/tests/test_miscellaneous1.json
> +    "message": "2023-06-07 04:26:17.306 +0200 60198 INFO null: MnT purge event occurred, MESSAGE=completed successfully,"
event.outcome doesn't seem to appear in the test, we'll see that later with @squioc

2023-06-23 13:32 UTC, Adamowoc approved these changes

2023-06-23 13:41 UTC, Adamowoc commented on Cisco/cisco-ise/_meta/manifest.yml
> +name: Cisco ISE
```suggestion
name: Cisco ISE [BETA]
```

2023-06-23 14:06 UTC, Adamowoc approved these changes

2023-06-26 10:55 UTC, squioc approved these changes
LGTM

2023-06-27 13:59 UTC, squioc approved these changes

2023-06-27 14:00 UTC, merged