feat(intake-formats): migrate umbrella-ip to ingest
SEKOIA-IO/intake-formats pull request #587
Opened 2023-06-27 08:11 UTC by yosradirgham

Umbrella-ip migration to ingest

2023-06-27 08:17 UTC, PierrickV approved these changes

2023-06-28 16:23 UTC, squioc requested changes

2023-06-28 16:23 UTC, squioc commented on Umbrella/umbrella-ip/ingest/parser.yml
> +          log.hostname: "{{parsed_event.message.log_hostname}}"
As `host.name` is more suitable, I suggest removing this line.
```suggestion
```

2024-03-06 10:50 UTC, squioc approved these changes
LGTM

2024-03-11 09:17 UTC, merged