feat(intake-formats): migrate fortiweb to ingest
SEKOIA-IO/intake-formats pull request #593
Opened 2023-06-27 13:00 UTC by yosradirgham

Fortiweb

2023-06-27 13:06 UTC, PierrickV commented on Fortinet/fortiweb/ingest/parser.yml
> +        value_sep: "="
```suggestion        
        value_sep: "="
        item_sep: \s
```

2023-07-05 09:55 UTC, squioc requested changes

2023-07-05 09:55 UTC, squioc commented on Fortinet/fortiweb/_meta/fields.yml
> +  type: keyword
These fields are useless
```suggestion
```

2023-07-05 09:55 UTC, squioc commented on Fortinet/fortiweb/ingest/parser.yml
> +          tmp.log_id: "{{parsed_event.message.time}}"
```suggestion
          device.id: "{{parsed_event.message.device_id}}"
```

2024-04-12 10:34 UTC, squioc approved these changes
LGTM

2024-04-18 09:46 UTC, squioc approved these changes

2024-04-18 09:47 UTC, merged