feat(Imperva): add waf parser
SEKOIA-IO/intake-formats pull request #63
Opened 2022-03-24 14:30 UTC by LeoArurault

New ingest parser for Imperva WAF

2022-03-24 14:32 UTC, otetard commented on Imperva/imperva-waf/_meta/fields.yml
> +  description: The threat rule name that this request triggered. For example, SQL Injection or Blocked IP (ACL).
Should probably be replaced by `rule.name`

2022-03-24 14:37 UTC, otetard commented on Imperva/imperva-waf/_meta/fields.yml
> +  description: The account name of the site owner.
Not sure that we will use that information to write detection or hunting rules. Am I wrong?

2022-03-24 14:38 UTC, otetard commented on Imperva/imperva-waf/_meta/fields.yml
> +  description: The X-Forwarded-For request header.
_May_ be replaced by `network.forwarded_ip` (not sure about this).

2022-03-24 15:08 UTC, squioc requested changes
LGTM unless the `imperva.rule.name` to rename with `rule.name`

2022-03-25 14:43 UTC, LeoArurault commented
After discussions with SQU, `rule.name` will contain original string as "signature generating the event", while the parsed version will be stored as a list in `imperva.rule.name`

2022-03-25 14:45 UTC, squioc approved these changes

2022-03-25 15:31 UTC, merged