Add google reports drive parser
SEKOIA-IO/intake-formats pull request #674
Opened 2023-08-08 09:13 UTC by TOUFIKIzakarya

Hi @Adamowoc 

You will find here the Google drive reports parser linked with this [connector](https://github.com/SEKOIA-IO/automation-library/pull/152)

2023-08-09 15:47 UTC, Adamowoc requested changes
Thank you for your work :)

2023-08-09 15:47 UTC, Adamowoc commented on Google Cloud/google-drive-reports/_meta/fields.yml
> +  description: ""
Could you add a few descriptions ?

2023-08-09 15:47 UTC, Adamowoc commented on Google Cloud/google-drive-reports/ingest/parser.yml
> +          google-drive-reports.parameters.owner: '{% for param in json_event.message.events[0].parameters %}{% if param.name == "owner" %}{{param.value}}{% endif %}{% endfor %}'
You can use the ecs field [file.owner](https://www.elastic.co/guide/en/ecs/8.6/ecs-file.html#field-file-owner)

2023-08-09 15:47 UTC, Adamowoc commented on Google Cloud/google-drive-reports/ingest/parser.yml
> +          google-drive-reports.parameters.doc_type: '{% for param in json_event.message.events[0].parameters %}{% if param.name == "doc_type" %}{{param.value}}{% endif %}{% endfor %}'
You can use the ecs field [file.type](https://www.elastic.co/guide/en/ecs/8.6/ecs-file.html#field-file-type)

2023-08-09 15:47 UTC, Adamowoc commented on Google Cloud/google-drive-reports/tests/test_drive_sample1.json
> +    "message": "{\"kind\":\"audit#activity\",\"id\":{\"time\":\"2014-03-17T15:39:18.460Z\",\"uniqQualifier\":\"reports unique ID\",\"applicationName\":\"drive\",\"customerId\":\"ABC123xyz\"},\"actor\
It would be nice to parse the actor email.

2023-08-09 15:47 UTC, Adamowoc commented on Google Cloud/google-drive-reports/ingest/parser.yml
> +      - set:
Can you set the `@timestamp` please ?

2023-08-09 15:47 UTC, Adamowoc commented on Google Cloud/google-drive-reports/ingest/parser.yml
> +          event.type: ["access"]
According to the `\"events\":[{\"type\":\"access\",\"name\":\"edit\"` in the examples provided, I think `event.type` should be in this case `["access", "edit"]`

2023-08-10 08:04 UTC, TOUFIKIzakarya commented on Google Cloud/google-drive-reports/tests/test_drive_sample.json
> +    "message": "{\"kind\":\"audit#activity\",\"id\":{\"time\":\"2014-03-17T15:39:18.460Z\",\"uniqQualifier\":\"reports unique ID\",\"applicationName\":\"drive\",\"customerId\":\"ABC123xyz\"},\"actor\
I think [file.gid](https://www.elastic.co/guide/en/ecs/8.6/ecs-file.html#field-file-gid) can be more suitable

2023-08-10 12:28 UTC, Adamowoc requested changes
Thank you for these changes

2023-08-10 12:28 UTC, Adamowoc commented on Google Cloud/google-drive-reports/ingest/parser.yml
> +          user.email: "{{json_event.message.actor.email}}"
I think the user != customer, so maybe we should create a custom field for this email. Also, we created a duplicate with l.25

2023-08-10 12:28 UTC, Adamowoc commented on Google Cloud/google-drive-reports/ingest/parser.yml
> +          event.type: ["access", "edit"]
This should change depending on the event. By default, just `"access" `seems good. 
If we believe [this documentation](https://support.google.com/a/answer/4579696?hl=en) Event name can be set to `View, Rename, Create, Edit, Preview, Print, Update, Delete, Upload, Download, Share a Drive file, or Connected Sheets refreshed objects`

2023-08-17 09:01 UTC, Adamowoc requested changes

2023-08-17 10:10 UTC, TOUFIKIzakarya commented on Google Cloud/google-drive-reports/ingest/parser.yml
> +        filter: '{{ json_event.message.actor.callerType == "USER"}}'
I think yes the USER in this case mean the customer of the Drive application. And also it's mentioned by Sébastien in the spec file.

2023-08-17 12:04 UTC, Adamowoc approved these changes

2023-08-18 12:12 UTC, merged