Add stromshield endpoint security to parsers
SEKOIA-IO/intake-formats pull request #679
Opened 2023-08-11 08:57 UTC by TOUFIKIzakarya

- Add stromshield endpoint security format 

[Link to specification](https://docs.google.com/document/d/16RyEAbI196y-05hR0Apu7cyBZ6kB47mWc1znleD194I/edit#heading=h.ata5uky5gsnf)

2023-08-18 08:48 UTC, Adamowoc submitted a review, later dismissed

2023-08-18 14:16 UTC, TOUFIKIzakarya commented on Stormshield/stormshield-endpoint-security/ingest/parser.yml
> +          file.owner: "{{json_event.message.SpecificData.FileOwnerNameLookupp}}"
You are right, in the doc it's `Lookupp`, but in samples it's `Lookup`

2023-08-18 14:54 UTC, TOUFIKIzakarya commented on Stormshield/stormshield-endpoint-security/ingest/parser.yml
> +          stormshield.process.user.domain: "{{json_event.message.SpecificData.SourceProcess.UserDomainLookup}}"
`process.user.domain` didn't work I had a taxonomy error even if this's the corresponding field in the ECS documentation.

2023-08-21 10:24 UTC, squioc requested changes
Thanks for the work.

Some changes requested.

2023-08-21 10:24 UTC, squioc commented on Stormshield/stormshield-endpoint-security/_meta/fields.yml
> +  name: stormshield.process.user.domain
suggest using `stormshield.ses` as prefix:
 ```suggestion
stormshield.ses.process.user.domain:
  type: keyword
  description: Name of the directory the user is a member of
  name: stormshield.ses.process.user.domain
```

2023-08-21 10:24 UTC, squioc commented on Stormshield/stormshield-endpoint-security/_meta/fields.yml
> +  name: stormshield.process.parent.user.domain
I suggest using `stormshield.ses` as prefix
 ```suggestion
stormshield.ses.process.parent.user.domain:
  type: keyword
  description: User's domain associated with the parent process of the event
  name: stormshield.ses.process.parent.user.domain
```

2023-08-21 10:24 UTC, squioc commented on Stormshield/stormshield-endpoint-security/_meta/fields.yml
> +  name: stormshield.type
I suggest using `stormshield.ses` as prefix:
```suggestion
stormshield.ses.type:
  type: keyword
  description: Event Type ( it's a number )
  name: stormshield.ses.type
```

2023-08-21 10:24 UTC, squioc commented on Stormshield/stormshield-endpoint-security/_meta/fields.yml
> +  name: stormshield.specificData.targetProcess.processcommandline
I suggest using `stormshield.ses` as prefix and `process.target.command_line`  for the name of the :
```suggestion
stormshield.ses.process.target.command_line:
  type: keyword
  description: stormshield process command line
  name: stormshield.ses.process.target.command_line
```

2023-09-14 16:28 UTC, squioc approved these changes

2023-09-14 16:43 UTC, merged