Add ekinops for the first time
SEKOIA-IO/intake-formats pull request #941
Opened 2024-02-22 09:28 UTC by TOUFIKIzakarya

- Add the ekinops parser for the first time

2024-02-23 15:25 UTC, vg-svitla commented
Looks good to me! Can you please check if prettier is applied to jsons? It will automatically add end lines where necessary etc

2024-02-23 15:29 UTC, vg-svitla submitted a review, later dismissed

2024-02-26 08:11 UTC, TOUFIKIzakarya commented on Ekinops/ekinops-oneos/CHANGELOG.md
> +## 2024-02-21
yes you're right. I think we have to do that

2024-02-26 08:16 UTC, TOUFIKIzakarya commented
Thanks @vg-svitla 👌🏻

2024-02-26 08:38 UTC, vg-svitla submitted a review, later dismissed

2024-02-26 16:28 UTC, squioc requested changes
LGTM.
Can you add the beta flag in the name of the format?

2024-02-26 16:28 UTC, squioc commented on Ekinops/ekinops-oneos/_meta/manifest.yml
> +name: Ekinops OneOS
```suggestion
name: Ekinops OneOS [BETA]
```

2024-02-26 16:40 UTC, squioc approved these changes

2024-02-27 08:44 UTC, merged